/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask */
        post: operations["ask_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get All Sessions */
        get: operations["get_all_sessions_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session By Id */
        get: operations["get_session_by_id_sessions__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge/index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Index Workspace
         * @description Triggers indexing on a local file path.
         */
        post: operations["index_workspace_knowledge_index_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search Knowledge
         * @description Performs semantic search across all indexed chunks.
         */
        post: operations["search_knowledge_knowledge_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspace/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Projects
         * @description Scans the workspace directory and lists discovered repositories and projects.
         */
        get: operations["get_projects_workspace_projects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kernel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Kernel Status */
        get: operations["get_kernel_status_kernel_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/telemetry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Telemetry Status */
        get: operations["get_telemetry_status_telemetry_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/missions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Missions */
        get: operations["list_missions_missions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/missions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Mission */
        get: operations["get_mission_missions__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/missions/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Mission */
        post: operations["start_mission_missions_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/missions/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause Mission */
        post: operations["pause_mission_missions_pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/missions/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Mission */
        post: operations["resume_mission_missions_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/missions/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Mission */
        post: operations["cancel_mission_missions_cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/missions/{id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Mission Action */
        post: operations["confirm_mission_action_missions__id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sse Endpoint */
        get: operations["sse_endpoint_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Workflows
         * @description List all registered workflows with current execution status.
         */
        get: operations["list_workflows_workflows_get"];
        put?: never;
        /**
         * Create Workflow
         * @description Create a new workflow from a node definition or from a built-in template.
         *     If template_id is provided, nodes are generated from the template.
         */
        post: operations["create_workflow_workflows_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Templates
         * @description List all built-in workflow templates.
         */
        get: operations["get_templates_workflows_templates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{workflow_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Workflow
         * @description Get a workflow by ID including current node states.
         */
        get: operations["get_workflow_workflows__workflow_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{workflow_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Workflow
         * @description Start workflow execution. Returns the new run_id.
         */
        post: operations["start_workflow_workflows__workflow_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{workflow_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pause Workflow
         * @description Pause a running workflow at the next safe checkpoint.
         */
        post: operations["pause_workflow_workflows__workflow_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{workflow_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume Workflow
         * @description Resume a paused workflow.
         */
        post: operations["resume_workflow_workflows__workflow_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{workflow_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Workflow
         * @description Cancel an active workflow execution.
         */
        post: operations["cancel_workflow_workflows__workflow_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{workflow_id}/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restart Workflow
         * @description Cancel the current run and start a fresh one.
         */
        post: operations["restart_workflow_workflows__workflow_id__restart_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{workflow_id}/retry/{node_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry Node
         * @description Reset a failed node to PENDING so it will be retried.
         */
        post: operations["retry_node_workflows__workflow_id__retry__node_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{workflow_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Workflow History
         * @description Get all execution run records for a workflow.
         */
        get: operations["get_workflow_history_workflows__workflow_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Active Workflows
         * @description Returns all currently running workflow summaries (for Kernel telemetry).
         */
        get: operations["get_active_workflows_workflows_active_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionConfirmRequest */
        ActionConfirmRequest: {
            /** Approved */
            approved: boolean;
        };
        /** AskRequest */
        AskRequest: {
            /**
             * Prompt
             * @description The query prompt sent to ORION
             * @example Hello
             */
            prompt: string;
            /**
             * Confirmed
             * @description Whether a potentially destructive action is confirmed
             * @default false
             */
            confirmed: boolean | null;
            /**
             * Confirmation Token
             * @description Correlation token confirming a blocked action
             */
            confirmation_token?: string | null;
        };
        /** AskResponse */
        AskResponse: {
            /**
             * Success
             * @description Whether the request processing succeeded
             */
            success: boolean;
            /**
             * Intent
             * @description The classified intent of the user prompt
             */
            intent: string;
            /**
             * Response
             * @description The response generated by the system
             */
            response: string;
            /**
             * Tool Used
             * @description The tool executed, if any
             */
            tool_used?: string | null;
            /**
             * Tool Output
             * @description The tool execution output, if any
             */
            tool_output?: string | null;
            /**
             * Session Id
             * @description The session identifier
             */
            session_id: string;
            /**
             * Execution Time Ms
             * @description The execution duration in milliseconds
             */
            execution_time_ms: number;
            /** @description Generative telemetry statistics */
            telemetry?: components["schemas"]["TelemetryDetail"] | null;
            /**
             * Confirmation Required
             * @description Indicates if user confirmation is required to proceed
             * @default false
             */
            confirmation_required: boolean | null;
            /**
             * Confirmation Token
             * @description Unique token for confirming this action
             */
            confirmation_token?: string | null;
        };
        /** ChatRequest */
        ChatRequest: {
            /**
             * Prompt
             * @description The query prompt sent to ORION
             */
            prompt: string;
            /**
             * Session Id
             * @description The session ID to persist history
             */
            session_id?: string | null;
            /**
             * Stream
             * @description Set to true to stream tokens dynamically
             * @default false
             */
            stream: boolean;
            /**
             * Confirmed
             * @description Whether a potentially destructive action is confirmed
             * @default false
             */
            confirmed: boolean | null;
            /**
             * Confirmation Token
             * @description Correlation token confirming a blocked action
             */
            confirmation_token?: string | null;
        };
        /** ConditionConfigRequest */
        ConditionConfigRequest: {
            /**
             * Type
             * @default boolean
             */
            type: string;
            /**
             * Params
             * @default {}
             */
            params: {
                [key: string]: unknown;
            };
            /** On True */
            on_true?: string | null;
            /** On False */
            on_false?: string | null;
        };
        /** CreateWorkflowRequest */
        CreateWorkflowRequest: {
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Flow Type
             * @default SEQUENTIAL
             */
            flow_type: string;
            /** Template Id */
            template_id?: string | null;
            /**
             * Tags
             * @default []
             */
            tags: string[];
            /** Timeout Seconds */
            timeout_seconds?: number | null;
            /**
             * Max Retries
             * @default 0
             */
            max_retries: number;
            /**
             * Nodes
             * @default []
             */
            nodes: components["schemas"]["WorkflowNodeRequest"][];
            /**
             * Variables
             * @default {}
             */
            variables: {
                [key: string]: unknown;
            };
        };
        /** DetailedMissionResponse */
        DetailedMissionResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Status */
            status: string;
            /** Priority */
            priority: string;
            /** Type */
            type: string;
            /** Workflow Id */
            workflow_id?: string | null;
            /** Progress */
            progress: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Currentstep */
            currentStep: string;
            /** Steps */
            steps: string[];
            /** Durationms */
            durationMs: number;
            /** Startedat */
            startedAt?: string | null;
            /** Finishedat */
            finishedAt?: string | null;
            /** Error */
            error?: string | null;
            /** Currenttool */
            currentTool?: string | null;
            /** Workflowname */
            workflowName?: string | null;
            /** Logs */
            logs: components["schemas"]["LogEntryResponse"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @description The operational status of the API
             * @default online
             */
            status: string;
            /**
             * Assistant
             * @description The name of the system assistant agent
             * @default ORION
             */
            assistant: string;
            /**
             * Version
             * @description The configuration version
             * @default 0.2
             */
            version: string;
            /**
             * Services
             * @description Detailed list of kernel subsystem heartbeats
             */
            services?: {
                [key: string]: unknown;
            }[] | null;
        };
        /** KernelStatusResponse */
        KernelStatusResponse: {
            /** Kernel State */
            kernel_state: string;
            /** Boot Time Ms */
            boot_time_ms: number;
            /** Registered Services Count */
            registered_services_count: number;
            /** Uptime */
            uptime: string;
            /** Cpu Utilization */
            cpu_utilization: number;
            /** Memory Usage Bytes */
            memory_usage_bytes: number;
            /** Health */
            health: {
                [key: string]: unknown;
            };
        };
        /** KnowledgeIndexRequest */
        KnowledgeIndexRequest: {
            /**
             * Path
             * @description Absolute folder path to index. Defaults to system workspace root.
             */
            path?: string | null;
            /**
             * Project Name
             * @description Display name for the indexed project.
             */
            project_name?: string | null;
        };
        /** KnowledgeIndexResponse */
        KnowledgeIndexResponse: {
            /** Success */
            success: boolean;
            /** Indexed Chunks */
            indexed_chunks: number;
            /** Message */
            message: string;
        };
        /** KnowledgeSearchRequest */
        KnowledgeSearchRequest: {
            /**
             * Query
             * @description Semantic search query text.
             */
            query: string;
            /**
             * N Results
             * @description Maximum matching document chunks to return.
             * @default 5
             */
            n_results: number | null;
        };
        /** KnowledgeSearchResponse */
        KnowledgeSearchResponse: {
            /** Success */
            success: boolean;
            /** Results */
            results: components["schemas"]["KnowledgeSearchResultDetail"][];
        };
        /** KnowledgeSearchResultDetail */
        KnowledgeSearchResultDetail: {
            /** Id */
            id: string;
            /** Document */
            document: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Score */
            score: number;
        };
        /** LogEntryResponse */
        LogEntryResponse: {
            /** Time */
            time: string;
            /** Level */
            level: string;
            /** Msg */
            msg: string;
        };
        /** MessageDetail */
        MessageDetail: {
            /** Role */
            role: string;
            /** Content */
            content: string;
            /** Timestamp */
            timestamp: number;
        };
        /** ProjectDetailResponse */
        ProjectDetailResponse: {
            /** Name */
            name: string;
            /** Path */
            path: string;
            /** Is Git */
            is_git: boolean;
            /** Branch */
            branch?: string | null;
            /** Files Count */
            files_count: number;
            /** Languages */
            languages: string[];
        };
        /** SessionDetailResponse */
        SessionDetailResponse: {
            /** Session Id */
            session_id: string;
            /** Messages */
            messages?: components["schemas"]["MessageDetail"][];
            /** Created At */
            created_at: number;
            /** Summary */
            summary?: string | null;
            /** Context */
            context?: string | null;
            /** Tool Used */
            tool_used?: string | null;
            /** Tool Output */
            tool_output?: string | null;
        };
        /** StatusToggleResponse */
        StatusToggleResponse: {
            /** Success */
            success: boolean;
            /** Mission Id */
            mission_id: string;
            /** Status */
            status: string;
        };
        /** TelemetryDetail */
        TelemetryDetail: {
            /**
             * Model
             * @description Model provider key
             */
            model: string;
            /**
             * Prompt Tokens
             * @description Tokens used for prompt
             * @default 0
             */
            prompt_tokens: number;
            /**
             * Completion Tokens
             * @description Tokens used for completion
             * @default 0
             */
            completion_tokens: number;
            /**
             * Total Tokens
             * @description Total tokens used
             * @default 0
             */
            total_tokens: number;
            /**
             * Error
             * @description Error details, if any
             */
            error?: string | null;
        };
        /** TelemetryResponse */
        TelemetryResponse: {
            /** Latency */
            latency: number;
            /** Fps */
            fps: number;
            /** Memory */
            memory: number;
            /** Executiontimems */
            executionTimeMs: number;
            /** Eventscount */
            eventsCount: number;
            /** Currenttool */
            currentTool: string;
            /** Workflow */
            workflow: string;
            /** Missionid */
            missionId: string;
            /** Current Desktop Task */
            current_desktop_task: string;
            /** Last Executed Action */
            last_executed_action: string;
            /** Average Execution Time Ms */
            average_execution_time_ms: number;
            /** Failure Count */
            failure_count: number;
            /** Queue Length */
            queue_length: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkflowActionResponse */
        WorkflowActionResponse: {
            /** Success */
            success: boolean;
            /** Workflow Id */
            workflow_id: string;
            /** Message */
            message: string;
            /** Run Id */
            run_id?: string | null;
        };
        /** WorkflowNodeRequest */
        WorkflowNodeRequest: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /**
             * Flow Type
             * @default SEQUENTIAL
             */
            flow_type: string;
            /**
             * Depends On
             * @default []
             */
            depends_on: string[];
            /** On Success */
            on_success?: string | null;
            /** On Failure */
            on_failure?: string | null;
            /**
             * Inputs
             * @default {}
             */
            inputs: {
                [key: string]: unknown;
            };
            /**
             * Max Retries
             * @default 0
             */
            max_retries: number;
            /**
             * Delay Seconds
             * @default 0
             */
            delay_seconds: number;
            /**
             * Loop Max
             * @default 1
             */
            loop_max: number;
            condition?: components["schemas"]["ConditionConfigRequest"] | null;
            /**
             * Metadata
             * @default {}
             */
            metadata: {
                [key: string]: unknown;
            };
        };
        /** WorkflowNodeResponse */
        WorkflowNodeResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Status */
            status: string;
            /** Flow Type */
            flow_type: string;
            /** Depends On */
            depends_on: string[];
            /** On Success */
            on_success: string | null;
            /** On Failure */
            on_failure: string | null;
            /** Inputs */
            inputs: {
                [key: string]: unknown;
            };
            /** Outputs */
            outputs: {
                [key: string]: unknown;
            };
            /** Error */
            error: string | null;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Retry Count */
            retry_count: number;
            /** Loop Count */
            loop_count: number;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
        };
        /** WorkflowResponse */
        WorkflowResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Status */
            status: string;
            /** Flow Type */
            flow_type: string;
            /** Template Id */
            template_id: string | null;
            /** Tags */
            tags: string[];
            /** Nodes */
            nodes: {
                [key: string]: components["schemas"]["WorkflowNodeResponse"];
            };
            /** Variables */
            variables: {
                [key: string]: unknown;
            };
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Error */
            error: string | null;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
        };
        /** WorkflowRunResponse */
        WorkflowRunResponse: {
            /** Run Id */
            run_id: string;
            /** Workflow Id */
            workflow_id: string;
            /** Workflow Name */
            workflow_name: string;
            /** Status */
            status: string;
            /** Current Node Id */
            current_node_id: string | null;
            /** Completed Nodes */
            completed_nodes: string[];
            /** Failed Nodes */
            failed_nodes: string[];
            /** Total Retries */
            total_retries: number;
            /** Duration Seconds */
            duration_seconds: number;
            /** Error */
            error: string | null;
            /** Branch Decisions */
            branch_decisions: {
                [key: string]: unknown;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ask_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_sessions_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetailResponse"][];
                };
            };
        };
    };
    get_session_by_id_sessions__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    index_workspace_knowledge_index_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeIndexRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeIndexResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_knowledge_knowledge_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_projects_workspace_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetailResponse"][];
                };
            };
        };
    };
    get_kernel_status_kernel_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KernelStatusResponse"];
                };
            };
        };
    };
    get_telemetry_status_telemetry_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelemetryResponse"];
                };
            };
        };
    };
    list_missions_missions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailedMissionResponse"][];
                };
            };
        };
    };
    get_mission_missions__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailedMissionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_mission_missions_start_post: {
        parameters: {
            query: {
                mission_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusToggleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_mission_missions_pause_post: {
        parameters: {
            query: {
                mission_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusToggleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_mission_missions_resume_post: {
        parameters: {
            query: {
                mission_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusToggleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_mission_missions_cancel_post: {
        parameters: {
            query: {
                mission_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusToggleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_mission_action_missions__id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionConfirmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sse_endpoint_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_workflows_workflows_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowResponse"][];
                };
            };
        };
    };
    create_workflow_workflows_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkflowRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_templates_workflows_templates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    get_workflow_workflows__workflow_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_workflow_workflows__workflow_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_workflow_workflows__workflow_id__pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_workflow_workflows__workflow_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_workflow_workflows__workflow_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restart_workflow_workflows__workflow_id__restart_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_node_workflows__workflow_id__retry__node_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workflow_history_workflows__workflow_id__history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowRunResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_active_workflows_workflows_active_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
}
