from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any

class HealthResponse(BaseModel):
    status: str = Field(default="online", description="The operational status of the API")
    assistant: str = Field(default="ORION", description="The name of the system assistant agent")
    version: str = Field(default="0.2", description="The configuration version")
    services: Optional[List[Dict[str, Any]]] = Field(default=None, description="Detailed list of kernel subsystem heartbeats")

class AskRequest(BaseModel):
    prompt: str = Field(..., description="The query prompt sent to ORION", examples=["Hello"])
    confirmed: Optional[bool] = Field(default=False, description="Whether a potentially destructive action is confirmed")
    confirmation_token: Optional[str] = Field(default=None, description="Correlation token confirming a blocked action")

class TelemetryDetail(BaseModel):
    model: str = Field(..., description="Model provider key")
    prompt_tokens: int = Field(default=0, description="Tokens used for prompt")
    completion_tokens: int = Field(default=0, description="Tokens used for completion")
    total_tokens: int = Field(default=0, description="Total tokens used")
    error: Optional[str] = Field(None, description="Error details, if any")

class AskResponse(BaseModel):
    success: bool = Field(..., description="Whether the request processing succeeded")
    intent: str = Field(..., description="The classified intent of the user prompt")
    response: str = Field(..., description="The response generated by the system")
    tool_used: Optional[str] = Field(None, description="The tool executed, if any")
    tool_output: Optional[str] = Field(None, description="The tool execution output, if any")
    session_id: str = Field(..., description="The session identifier")
    execution_time_ms: float = Field(..., description="The execution duration in milliseconds")
    telemetry: Optional[TelemetryDetail] = Field(None, description="Generative telemetry statistics")
    confirmation_required: Optional[bool] = Field(default=False, description="Indicates if user confirmation is required to proceed")
    confirmation_token: Optional[str] = Field(default=None, description="Unique token for confirming this action")

class ChatRequest(BaseModel):
    prompt: str = Field(..., description="The query prompt sent to ORION")
    session_id: Optional[str] = Field(None, description="The session ID to persist history")
    stream: bool = Field(default=False, description="Set to true to stream tokens dynamically")
    confirmed: Optional[bool] = Field(default=False, description="Whether a potentially destructive action is confirmed")
    confirmation_token: Optional[str] = Field(default=None, description="Correlation token confirming a blocked action")

class MessageDetail(BaseModel):
    role: str
    content: str
    timestamp: float

class SessionDetailResponse(BaseModel):
    session_id: str
    messages: List[MessageDetail] = Field(default_factory=list)
    created_at: float
    summary: Optional[str] = None
    context: Optional[str] = None
    tool_used: Optional[str] = None
    tool_output: Optional[str] = None

# ---------- Alpha 1.2: Knowledge Engine Schemas ----------

class KnowledgeIndexRequest(BaseModel):
    path: Optional[str] = Field(None, description="Absolute folder path to index. Defaults to system workspace root.")
    project_name: Optional[str] = Field(None, description="Display name for the indexed project.")

class KnowledgeIndexResponse(BaseModel):
    success: bool
    indexed_chunks: int
    message: str

class KnowledgeSearchRequest(BaseModel):
    query: str = Field(..., description="Semantic search query text.")
    n_results: Optional[int] = Field(default=5, description="Maximum matching document chunks to return.")

class KnowledgeSearchResultDetail(BaseModel):
    id: str
    document: str
    metadata: Dict[str, Any]
    score: float

class KnowledgeSearchResponse(BaseModel):
    success: bool
    results: List[KnowledgeSearchResultDetail]

class ProjectDetailResponse(BaseModel):
    name: str
    path: str
    is_git: bool
    branch: Optional[str] = None
    files_count: int
    languages: List[str]
