from pydantic import BaseModel, Field
from typing import Optional

class OrionTelemetry(BaseModel):
    model: str = Field(..., description="The chosen model provider")
    prompt_tokens: int = Field(default=0, description="Tokens used for prompt")
    completion_tokens: int = Field(default=0, description="Tokens used for completion")
    total_tokens: int = Field(default=0, description="Total tokens used")
    error: Optional[str] = Field(None, description="Error details, if any")

class OrionResponse(BaseModel):
    """
    Standard response schema for queries processed by the ORION Orchestrator.
    """
    success: bool = Field(..., description="Whether the operation succeeded")
    intent: str = Field(..., description="The classified user intent")
    response: str = Field(..., description="The textual response generated by the system")
    tool_used: Optional[str] = Field(None, description="The tool executed, if any")
    session_id: str = Field(..., description="The session identifier")
    execution_time_ms: float = Field(..., description="The query processing duration in milliseconds")
    telemetry: Optional[OrionTelemetry] = Field(None, description="Generative telemetry statistics")
    confirmation_required: Optional[bool] = Field(default=False, description="Whether user confirmation is required")
    confirmation_token: Optional[str] = Field(default=None, description="Correlation token confirming a blocked action")
